import type { Stage, Feature, Metric, QuickStartStep } from "./types";

export const STAGES: Stage[] = [
  {
    id: "01-brainstorm",
    number: "01",
    name: "Brainstorming",
    description: "Divergent idea generation and requirements exploration with creative AI models working in parallel.",
    aiModel: "gemini",
    aiModelLabel: "Gemini + Claude",
    executionMode: "YOLO (Container)",
    inputs: ["project_brief.md"],
    outputs: ["ideas.md", "requirements_analysis.md"],
    color: "#10b981",
  },
  {
    id: "02-research",
    number: "02",
    name: "Research",
    description: "Technical research, market analysis, and feasibility assessment with deep analytical capabilities.",
    aiModel: "claude",
    aiModelLabel: "Claude",
    executionMode: "Plan Mode",
    inputs: ["ideas.md"],
    outputs: ["tech_research.md", "feasibility_report.md"],
    color: "#8b5cf6",
  },
  {
    id: "03-planning",
    number: "03",
    name: "Planning",
    description: "System architecture design, technology stack decisions, and project plan establishment.",
    aiModel: "gemini",
    aiModelLabel: "Gemini + Claude",
    executionMode: "Plan Mode",
    inputs: ["tech_research.md", "feasibility_report.md"],
    outputs: ["architecture.md", "project_plan.md"],
    color: "#10b981",
  },
  {
    id: "04-ui-ux",
    number: "04",
    name: "UI/UX Planning",
    description: "Wireframe design, user flow definition, and design system foundation with visual thinking.",
    aiModel: "gemini",
    aiModelLabel: "Gemini + Claude",
    executionMode: "Plan Mode",
    inputs: ["architecture.md"],
    outputs: ["wireframes.md", "design_system.md"],
    color: "#10b981",
  },
  {
    id: "05-task-management",
    number: "05",
    name: "Task Management",
    description: "Feature-based task breakdown, dependency mapping, and sprint planning with precise organization.",
    aiModel: "claude",
    aiModelLabel: "Claude",
    executionMode: "Plan Mode",
    inputs: ["project_plan.md", "design_system.md"],
    outputs: ["tasks.md", "sprint_plan.md"],
    color: "#8b5cf6",
  },
  {
    id: "06-implementation",
    number: "06",
    name: "Implementation",
    description: "Core feature implementation following sprint plan with test-first methodology and sandbox execution.",
    aiModel: "claude",
    aiModelLabel: "Claude",
    executionMode: "Plan + Sandbox",
    inputs: ["tasks.md", "sprint_plan.md"],
    outputs: ["source_code/"],
    color: "#8b5cf6",
  },
  {
    id: "07-refactoring",
    number: "07",
    name: "Refactoring",
    description: "Deep code analysis, performance optimization, and architectural improvements with surgical precision.",
    aiModel: "codex",
    aiModelLabel: "Codex + Claude",
    executionMode: "Deep Dive",
    inputs: ["source_code/"],
    outputs: ["refactoring_report.md"],
    color: "#f59e0b",
  },
  {
    id: "08-qa",
    number: "08",
    name: "QA",
    description: "Quality assurance with thorough verification, risk detection, and bug tracking across all features.",
    aiModel: "claude",
    aiModelLabel: "Claude",
    executionMode: "Plan + Sandbox",
    inputs: ["source_code/", "refactoring_report.md"],
    outputs: ["qa_report.md"],
    color: "#8b5cf6",
  },
  {
    id: "09-testing",
    number: "09",
    name: "Testing & E2E",
    description: "Comprehensive test suite with unit, integration, and end-to-end testing using Playwright.",
    aiModel: "codex",
    aiModelLabel: "Codex + Claude",
    executionMode: "Sandbox + Playwright",
    inputs: ["source_code/", "qa_report.md"],
    outputs: ["tests/", "coverage_report"],
    color: "#f59e0b",
  },
  {
    id: "10-deployment",
    number: "10",
    name: "CI/CD & Deployment",
    description: "Continuous integration, deployment pipelines, and production release with automated workflows.",
    aiModel: "claude",
    aiModelLabel: "Claude",
    executionMode: "Headless",
    inputs: ["source_code/", "tests/"],
    outputs: ["CI/CD workflows", "deployment"],
    color: "#8b5cf6",
  },
];

export const FEATURES: Feature[] = [
  {
    title: "Sub-Agent System",
    description: "Specialized agents run in isolated contexts, preserving your main session's context window entirely.",
    icon: "Cpu",
    highlight: "0% context usage",
  },
  {
    title: "10-Stage Pipeline",
    description: "Complete development cycle from brainstorming to deployment, every phase automated with specialized AI agents.",
    icon: "Workflow",
    highlight: "10 stages",
  },
  {
    title: "Multi-AI Orchestration",
    description: "Claude, Gemini, and Codex work together — each assigned to stages matching their strengths.",
    icon: "Brain",
    highlight: "3 AI providers",
  },
  {
    title: "Smart HANDOFF System",
    description: "Automatic context extraction and stage transition documents with semantic compression.",
    icon: "FileText",
    highlight: "Auto-compress",
  },
  {
    title: "Context Monitoring",
    description: "Context tracking via statusline with automatic state saves and compression strategies.",
    icon: "Activity",
    highlight: "Real-time tracking",
  },
  {
    title: "Auto-Checkpoint & Rollback",
    description: "Task-based triggers with partial rollback support, ensuring safe destructive operations.",
    icon: "Shield",
    highlight: "Smart rollback",
  },
  {
    title: "Pipeline Forking",
    description: "Explore architecture alternatives in parallel branches, compare results, and merge the best approach.",
    icon: "GitBranch",
    highlight: "A/B exploration",
  },
  {
    title: "Stage Personas",
    description: "Optimized AI behavior profiles per stage — from Creative Explorer to Quality Guardian.",
    icon: "Users",
    highlight: "6 personas",
  },
  {
    title: "Output Validation",
    description: "Automated quality checks with sub-agent fallback ensuring every stage meets quality thresholds.",
    icon: "CheckCircle",
    highlight: "80%+ quality",
  },
];

export const METRICS: Metric[] = [
  { value: 10, label: "Pipeline Stages" },
  { value: 109, suffix: "+", label: "Automated Tests" },
  { value: 5, prefix: "<", suffix: "ms", label: "Infrastructure Speed" },
  { value: 0, suffix: "%", label: "Context Usage (Sub-agents)" },
];

export const QUICK_START_STEPS: QuickStartStep[] = [
  { type: "command", text: "npx claude-symphony init" },
  { type: "output", text: "Initializing claude-symphony project...", delay: 800 },
  { type: "output", text: "Setting up 10-stage pipeline...", delay: 400 },
  { type: "output", text: "Configuring AI model assignments...", delay: 400 },
  { type: "output", text: "Generating stage templates...", delay: 300 },
  { type: "output", text: "✓ Project ready! Run: cd my-project", delay: 500 },
];

export const AI_COLORS: Record<string, string> = {
  claude: "#8b5cf6",
  gemini: "#10b981",
  codex: "#f59e0b",
};
